language: php
php:
  - 7.0
  - 7.1
  - 7.2
  - nightly
env:
  - PREFER_LOWEST="--prefer-lowest --prefer-stable"
  - PREFER_LOWEST=""
services: mongodb
matrix:
  fast_finish: true
  allow_failures:
     - php: nightly
before_script:
  - yes '' | pecl install -f mongodb-1.1
  - composer update $PREFER_LOWEST
script: ./vendor/bin/phpunit --coverage-clover clover.xml
after_success: ./vendor/bin/coveralls -v
